# Generated by Django 4.1.1 on 2022-10-08 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventario.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[inventario.validators.validar_nombre_categoria])),
            ],
            options={
                'permissions': [('reporte_cantidad', 'Visualizar el reporte de cantidad'), ('reporte_detalle', 'Reporte detallado de cantidades')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=50, unique=True, validators=[inventario.validators.validar_longitud_minima_texto])),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(max_length=30)),
                ('primerNombre', models.CharField(max_length=30)),
                ('otrosNombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitEmisor', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('nopagado', 'No Pagado'), ('pagado', 'Pagado')], default='nopagado', max_length=10)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_orden_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('municipio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('esCasaMatriz', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[inventario.validators.validar_par])),
                ('unidades', models.CharField(choices=[('u', 'Unidades'), ('kg', 'Kilogramos')], default='u', max_length=2)),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFactura', models.IntegerField(default=1)),
                ('cuf', models.CharField(max_length=52)),
                ('fecha', models.DateField()),
                ('metodoPago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('montoTotal', models.IntegerField(default=0)),
                ('montoTotalSujetoIva', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('valida', 'Válida'), ('anulada', 'Anulada')], default='valida', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_factura_cliente', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[inventario.validators.validar_cantidad_minima_items_factura])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'permissions': [('reporte_cantidad_items_factura', 'Visualizar el reporte de cantidad items factura'), ('reporte_detalle_items_factura', 'Reporte detalle items factura')],
            },
        ),
    ]
